// This file is @generated by prost-build.
/// Gov tx to add a new rate limit
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgAddRateLimit {
    /// signer defines the x/gov module account address or other authority signing the message
    #[prost(string, tag = "1")]
    pub signer: ::prost::alloc::string::String,
    /// Denom for the rate limit, as it appears on the rate limited chain
    /// When rate limiting a non-native token, this will be an ibc denom
    #[prost(string, tag = "2")]
    pub denom: ::prost::alloc::string::String,
    /// ChannelId for the rate limit, on the side of the rate limited chain
    #[prost(string, tag = "3")]
    pub channel_or_client_id: ::prost::alloc::string::String,
    /// MaxPercentSend defines the threshold for outflows
    /// The threshold is defined as a percentage (e.g. 10 indicates 10%)
    #[prost(string, tag = "4")]
    pub max_percent_send: ::prost::alloc::string::String,
    /// MaxPercentSend defines the threshold for inflows
    /// The threshold is defined as a percentage (e.g. 10 indicates 10%)
    #[prost(string, tag = "5")]
    pub max_percent_recv: ::prost::alloc::string::String,
    /// DurationHours specifies the number of hours before the rate limit
    /// is reset (e.g. 24 indicates that the rate limit is reset each day)
    #[prost(uint64, tag = "6")]
    pub duration_hours: u64,
}
impl ::prost::Name for MsgAddRateLimit {
    const NAME: &'static str = "MsgAddRateLimit";
    const PACKAGE: &'static str = "ibc.applications.rate_limiting.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "ibc.applications.rate_limiting.v1.MsgAddRateLimit".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/ibc.applications.rate_limiting.v1.MsgAddRateLimit".into()
    }
}
/// MsgAddRateLimitResponse is the return type for AddRateLimit function.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MsgAddRateLimitResponse {}
impl ::prost::Name for MsgAddRateLimitResponse {
    const NAME: &'static str = "MsgAddRateLimitResponse";
    const PACKAGE: &'static str = "ibc.applications.rate_limiting.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "ibc.applications.rate_limiting.v1.MsgAddRateLimitResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/ibc.applications.rate_limiting.v1.MsgAddRateLimitResponse".into()
    }
}
/// Gov tx to update an existing rate limit
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgUpdateRateLimit {
    /// signer defines the x/gov module account address or other authority signing the message
    #[prost(string, tag = "1")]
    pub signer: ::prost::alloc::string::String,
    /// Denom for the rate limit, as it appears on the rate limited chain
    /// When rate limiting a non-native token, this will be an ibc denom
    #[prost(string, tag = "2")]
    pub denom: ::prost::alloc::string::String,
    /// ChannelId for the rate limit, on the side of the rate limited chain
    #[prost(string, tag = "3")]
    pub channel_or_client_id: ::prost::alloc::string::String,
    /// MaxPercentSend defines the threshold for outflows
    /// The threshold is defined as a percentage (e.g. 10 indicates 10%)
    #[prost(string, tag = "4")]
    pub max_percent_send: ::prost::alloc::string::String,
    /// MaxPercentSend defines the threshold for inflows
    /// The threshold is defined as a percentage (e.g. 10 indicates 10%)
    #[prost(string, tag = "5")]
    pub max_percent_recv: ::prost::alloc::string::String,
    /// DurationHours specifies the number of hours before the rate limit
    /// is reset (e.g. 24 indicates that the rate limit is reset each day)
    #[prost(uint64, tag = "6")]
    pub duration_hours: u64,
}
impl ::prost::Name for MsgUpdateRateLimit {
    const NAME: &'static str = "MsgUpdateRateLimit";
    const PACKAGE: &'static str = "ibc.applications.rate_limiting.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "ibc.applications.rate_limiting.v1.MsgUpdateRateLimit".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/ibc.applications.rate_limiting.v1.MsgUpdateRateLimit".into()
    }
}
/// MsgUpdateRateLimitResponse is the return type for UpdateRateLimit.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MsgUpdateRateLimitResponse {}
impl ::prost::Name for MsgUpdateRateLimitResponse {
    const NAME: &'static str = "MsgUpdateRateLimitResponse";
    const PACKAGE: &'static str = "ibc.applications.rate_limiting.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "ibc.applications.rate_limiting.v1.MsgUpdateRateLimitResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/ibc.applications.rate_limiting.v1.MsgUpdateRateLimitResponse".into()
    }
}
/// Gov tx to remove a rate limit
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgRemoveRateLimit {
    /// signer defines the x/gov module account address or other authority signing the message
    #[prost(string, tag = "1")]
    pub signer: ::prost::alloc::string::String,
    /// Denom for the rate limit, as it appears on the rate limited chain
    /// When rate limiting a non-native token, this will be an ibc denom
    #[prost(string, tag = "2")]
    pub denom: ::prost::alloc::string::String,
    /// ChannelId for the rate limit, on the side of the rate limited chain
    #[prost(string, tag = "3")]
    pub channel_or_client_id: ::prost::alloc::string::String,
}
impl ::prost::Name for MsgRemoveRateLimit {
    const NAME: &'static str = "MsgRemoveRateLimit";
    const PACKAGE: &'static str = "ibc.applications.rate_limiting.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "ibc.applications.rate_limiting.v1.MsgRemoveRateLimit".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/ibc.applications.rate_limiting.v1.MsgRemoveRateLimit".into()
    }
}
/// MsgRemoveRateLimitResponse is the response type for RemoveRateLimit
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MsgRemoveRateLimitResponse {}
impl ::prost::Name for MsgRemoveRateLimitResponse {
    const NAME: &'static str = "MsgRemoveRateLimitResponse";
    const PACKAGE: &'static str = "ibc.applications.rate_limiting.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "ibc.applications.rate_limiting.v1.MsgRemoveRateLimitResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/ibc.applications.rate_limiting.v1.MsgRemoveRateLimitResponse".into()
    }
}
/// Gov tx to reset the flow on a rate limit
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgResetRateLimit {
    /// signer defines the x/gov module account address or other authority signing the message
    #[prost(string, tag = "1")]
    pub signer: ::prost::alloc::string::String,
    /// Denom for the rate limit, as it appears on the rate limited chain
    /// When rate limiting a non-native token, this will be an ibc denom
    #[prost(string, tag = "2")]
    pub denom: ::prost::alloc::string::String,
    /// ChannelId for the rate limit, on the side of the rate limited chain
    #[prost(string, tag = "3")]
    pub channel_or_client_id: ::prost::alloc::string::String,
}
impl ::prost::Name for MsgResetRateLimit {
    const NAME: &'static str = "MsgResetRateLimit";
    const PACKAGE: &'static str = "ibc.applications.rate_limiting.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "ibc.applications.rate_limiting.v1.MsgResetRateLimit".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/ibc.applications.rate_limiting.v1.MsgResetRateLimit".into()
    }
}
/// MsgResetRateLimitResponse is the response type for ResetRateLimit.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MsgResetRateLimitResponse {}
impl ::prost::Name for MsgResetRateLimitResponse {
    const NAME: &'static str = "MsgResetRateLimitResponse";
    const PACKAGE: &'static str = "ibc.applications.rate_limiting.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "ibc.applications.rate_limiting.v1.MsgResetRateLimitResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/ibc.applications.rate_limiting.v1.MsgResetRateLimitResponse".into()
    }
}
/// Generated client implementations.
#[cfg(feature = "client")]
pub mod msg_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Msg service for rate limit txs
    #[derive(Debug, Clone)]
    pub struct MsgClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    #[cfg(feature = "transport")]
    impl MsgClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> MsgClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> MsgClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            MsgClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Gov tx to add a new rate limit
        pub async fn add_rate_limit(
            &mut self,
            request: impl tonic::IntoRequest<super::MsgAddRateLimit>,
        ) -> std::result::Result<
            tonic::Response<super::MsgAddRateLimitResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/ibc.applications.rate_limiting.v1.Msg/AddRateLimit",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "ibc.applications.rate_limiting.v1.Msg",
                        "AddRateLimit",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Gov tx to update an existing rate limit
        pub async fn update_rate_limit(
            &mut self,
            request: impl tonic::IntoRequest<super::MsgUpdateRateLimit>,
        ) -> std::result::Result<
            tonic::Response<super::MsgUpdateRateLimitResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/ibc.applications.rate_limiting.v1.Msg/UpdateRateLimit",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "ibc.applications.rate_limiting.v1.Msg",
                        "UpdateRateLimit",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Gov tx to remove a rate limit
        pub async fn remove_rate_limit(
            &mut self,
            request: impl tonic::IntoRequest<super::MsgRemoveRateLimit>,
        ) -> std::result::Result<
            tonic::Response<super::MsgRemoveRateLimitResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/ibc.applications.rate_limiting.v1.Msg/RemoveRateLimit",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "ibc.applications.rate_limiting.v1.Msg",
                        "RemoveRateLimit",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Gov tx to reset the flow on a rate limit
        pub async fn reset_rate_limit(
            &mut self,
            request: impl tonic::IntoRequest<super::MsgResetRateLimit>,
        ) -> std::result::Result<
            tonic::Response<super::MsgResetRateLimitResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/ibc.applications.rate_limiting.v1.Msg/ResetRateLimit",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "ibc.applications.rate_limiting.v1.Msg",
                        "ResetRateLimit",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
#[cfg(feature = "server")]
pub mod msg_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with MsgServer.
    #[async_trait]
    pub trait Msg: std::marker::Send + std::marker::Sync + 'static {
        /// Gov tx to add a new rate limit
        async fn add_rate_limit(
            &self,
            request: tonic::Request<super::MsgAddRateLimit>,
        ) -> std::result::Result<
            tonic::Response<super::MsgAddRateLimitResponse>,
            tonic::Status,
        >;
        /// Gov tx to update an existing rate limit
        async fn update_rate_limit(
            &self,
            request: tonic::Request<super::MsgUpdateRateLimit>,
        ) -> std::result::Result<
            tonic::Response<super::MsgUpdateRateLimitResponse>,
            tonic::Status,
        >;
        /// Gov tx to remove a rate limit
        async fn remove_rate_limit(
            &self,
            request: tonic::Request<super::MsgRemoveRateLimit>,
        ) -> std::result::Result<
            tonic::Response<super::MsgRemoveRateLimitResponse>,
            tonic::Status,
        >;
        /// Gov tx to reset the flow on a rate limit
        async fn reset_rate_limit(
            &self,
            request: tonic::Request<super::MsgResetRateLimit>,
        ) -> std::result::Result<
            tonic::Response<super::MsgResetRateLimitResponse>,
            tonic::Status,
        >;
    }
    /// Msg service for rate limit txs
    #[derive(Debug)]
    pub struct MsgServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> MsgServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for MsgServer<T>
    where
        T: Msg,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/ibc.applications.rate_limiting.v1.Msg/AddRateLimit" => {
                    #[allow(non_camel_case_types)]
                    struct AddRateLimitSvc<T: Msg>(pub Arc<T>);
                    impl<T: Msg> tonic::server::UnaryService<super::MsgAddRateLimit>
                    for AddRateLimitSvc<T> {
                        type Response = super::MsgAddRateLimitResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::MsgAddRateLimit>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Msg>::add_rate_limit(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = AddRateLimitSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/ibc.applications.rate_limiting.v1.Msg/UpdateRateLimit" => {
                    #[allow(non_camel_case_types)]
                    struct UpdateRateLimitSvc<T: Msg>(pub Arc<T>);
                    impl<T: Msg> tonic::server::UnaryService<super::MsgUpdateRateLimit>
                    for UpdateRateLimitSvc<T> {
                        type Response = super::MsgUpdateRateLimitResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::MsgUpdateRateLimit>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Msg>::update_rate_limit(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = UpdateRateLimitSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/ibc.applications.rate_limiting.v1.Msg/RemoveRateLimit" => {
                    #[allow(non_camel_case_types)]
                    struct RemoveRateLimitSvc<T: Msg>(pub Arc<T>);
                    impl<T: Msg> tonic::server::UnaryService<super::MsgRemoveRateLimit>
                    for RemoveRateLimitSvc<T> {
                        type Response = super::MsgRemoveRateLimitResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::MsgRemoveRateLimit>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Msg>::remove_rate_limit(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = RemoveRateLimitSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/ibc.applications.rate_limiting.v1.Msg/ResetRateLimit" => {
                    #[allow(non_camel_case_types)]
                    struct ResetRateLimitSvc<T: Msg>(pub Arc<T>);
                    impl<T: Msg> tonic::server::UnaryService<super::MsgResetRateLimit>
                    for ResetRateLimitSvc<T> {
                        type Response = super::MsgResetRateLimitResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::MsgResetRateLimit>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Msg>::reset_rate_limit(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ResetRateLimitSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for MsgServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "ibc.applications.rate_limiting.v1.Msg";
    impl<T> tonic::server::NamedService for MsgServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
/// Path holds the denom and channelID that define the rate limited route
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Path {
    #[prost(string, tag = "1")]
    pub denom: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub channel_or_client_id: ::prost::alloc::string::String,
}
impl ::prost::Name for Path {
    const NAME: &'static str = "Path";
    const PACKAGE: &'static str = "ibc.applications.rate_limiting.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "ibc.applications.rate_limiting.v1.Path".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/ibc.applications.rate_limiting.v1.Path".into()
    }
}
/// Quota defines the rate limit thresholds for transfer packets
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Quota {
    /// MaxPercentSend defines the threshold for outflows
    /// The threshold is defined as a percentage (e.g. 10 indicates 10%)
    #[prost(string, tag = "1")]
    pub max_percent_send: ::prost::alloc::string::String,
    /// MaxPercentSend defines the threshold for inflows
    /// The threshold is defined as a percentage (e.g. 10 indicates 10%)
    #[prost(string, tag = "2")]
    pub max_percent_recv: ::prost::alloc::string::String,
    /// DurationHours specifies the number of hours before the rate limit
    /// is reset (e.g. 24 indicates that the rate limit is reset each day)
    #[prost(uint64, tag = "3")]
    pub duration_hours: u64,
}
impl ::prost::Name for Quota {
    const NAME: &'static str = "Quota";
    const PACKAGE: &'static str = "ibc.applications.rate_limiting.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "ibc.applications.rate_limiting.v1.Quota".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/ibc.applications.rate_limiting.v1.Quota".into()
    }
}
/// Flow tracks all the inflows and outflows of a channel.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Flow {
    /// Inflow defines the total amount of inbound transfers for the given
    /// rate limit in the current window
    #[prost(string, tag = "1")]
    pub inflow: ::prost::alloc::string::String,
    /// Outflow defines the total amount of outbound transfers for the given
    /// rate limit in the current window
    #[prost(string, tag = "2")]
    pub outflow: ::prost::alloc::string::String,
    /// ChannelValue stores the total supply of the denom at the start of
    /// the rate limit. This is used as the denominator when checking
    /// the rate limit threshold
    /// The ChannelValue is fixed for the duration of the rate limit window
    #[prost(string, tag = "3")]
    pub channel_value: ::prost::alloc::string::String,
}
impl ::prost::Name for Flow {
    const NAME: &'static str = "Flow";
    const PACKAGE: &'static str = "ibc.applications.rate_limiting.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "ibc.applications.rate_limiting.v1.Flow".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/ibc.applications.rate_limiting.v1.Flow".into()
    }
}
/// RateLimit stores all the context about a given rate limit, including
/// the relevant denom and channel, rate limit thresholds, and current
/// progress towards the limits
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RateLimit {
    #[prost(message, optional, tag = "1")]
    pub path: ::core::option::Option<Path>,
    #[prost(message, optional, tag = "2")]
    pub quota: ::core::option::Option<Quota>,
    #[prost(message, optional, tag = "3")]
    pub flow: ::core::option::Option<Flow>,
}
impl ::prost::Name for RateLimit {
    const NAME: &'static str = "RateLimit";
    const PACKAGE: &'static str = "ibc.applications.rate_limiting.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "ibc.applications.rate_limiting.v1.RateLimit".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/ibc.applications.rate_limiting.v1.RateLimit".into()
    }
}
/// WhitelistedAddressPair represents a sender-receiver combo that is
/// not subject to rate limit restrictions
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WhitelistedAddressPair {
    #[prost(string, tag = "1")]
    pub sender: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub receiver: ::prost::alloc::string::String,
}
impl ::prost::Name for WhitelistedAddressPair {
    const NAME: &'static str = "WhitelistedAddressPair";
    const PACKAGE: &'static str = "ibc.applications.rate_limiting.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "ibc.applications.rate_limiting.v1.WhitelistedAddressPair".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/ibc.applications.rate_limiting.v1.WhitelistedAddressPair".into()
    }
}
/// HourEpoch is the epoch type.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct HourEpoch {
    #[prost(uint64, tag = "1")]
    pub epoch_number: u64,
    #[prost(message, optional, tag = "2")]
    pub duration: ::core::option::Option<::tendermint_proto::google::protobuf::Duration>,
    #[prost(message, optional, tag = "3")]
    pub epoch_start_time: ::core::option::Option<
        ::tendermint_proto::google::protobuf::Timestamp,
    >,
    #[prost(int64, tag = "4")]
    pub epoch_start_height: i64,
}
impl ::prost::Name for HourEpoch {
    const NAME: &'static str = "HourEpoch";
    const PACKAGE: &'static str = "ibc.applications.rate_limiting.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "ibc.applications.rate_limiting.v1.HourEpoch".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/ibc.applications.rate_limiting.v1.HourEpoch".into()
    }
}
/// PacketDirection defines whether the transfer packet is being sent from
/// this chain or is being received on this chain
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum PacketDirection {
    PacketSend = 0,
    PacketRecv = 1,
}
impl PacketDirection {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::PacketSend => "PACKET_SEND",
            Self::PacketRecv => "PACKET_RECV",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PACKET_SEND" => Some(Self::PacketSend),
            "PACKET_RECV" => Some(Self::PacketRecv),
            _ => None,
        }
    }
}
/// Queries all rate limits
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct QueryAllRateLimitsRequest {}
impl ::prost::Name for QueryAllRateLimitsRequest {
    const NAME: &'static str = "QueryAllRateLimitsRequest";
    const PACKAGE: &'static str = "ibc.applications.rate_limiting.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "ibc.applications.rate_limiting.v1.QueryAllRateLimitsRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/ibc.applications.rate_limiting.v1.QueryAllRateLimitsRequest".into()
    }
}
/// QueryAllRateLimitsResponse returns all the rate limits stored on the chain.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryAllRateLimitsResponse {
    #[prost(message, repeated, tag = "1")]
    pub rate_limits: ::prost::alloc::vec::Vec<RateLimit>,
}
impl ::prost::Name for QueryAllRateLimitsResponse {
    const NAME: &'static str = "QueryAllRateLimitsResponse";
    const PACKAGE: &'static str = "ibc.applications.rate_limiting.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "ibc.applications.rate_limiting.v1.QueryAllRateLimitsResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/ibc.applications.rate_limiting.v1.QueryAllRateLimitsResponse".into()
    }
}
/// Queries a specific rate limit by channel ID and denom
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryRateLimitRequest {
    #[prost(string, tag = "1")]
    pub denom: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub channel_or_client_id: ::prost::alloc::string::String,
}
impl ::prost::Name for QueryRateLimitRequest {
    const NAME: &'static str = "QueryRateLimitRequest";
    const PACKAGE: &'static str = "ibc.applications.rate_limiting.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "ibc.applications.rate_limiting.v1.QueryRateLimitRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/ibc.applications.rate_limiting.v1.QueryRateLimitRequest".into()
    }
}
/// QueryRateLimitResponse returns a rate limit by denom and channel_or_client_id combination.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryRateLimitResponse {
    #[prost(message, optional, tag = "1")]
    pub rate_limit: ::core::option::Option<RateLimit>,
}
impl ::prost::Name for QueryRateLimitResponse {
    const NAME: &'static str = "QueryRateLimitResponse";
    const PACKAGE: &'static str = "ibc.applications.rate_limiting.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "ibc.applications.rate_limiting.v1.QueryRateLimitResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/ibc.applications.rate_limiting.v1.QueryRateLimitResponse".into()
    }
}
/// Queries all the rate limits for a given chain
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryRateLimitsByChainIdRequest {
    #[prost(string, tag = "1")]
    pub chain_id: ::prost::alloc::string::String,
}
impl ::prost::Name for QueryRateLimitsByChainIdRequest {
    const NAME: &'static str = "QueryRateLimitsByChainIDRequest";
    const PACKAGE: &'static str = "ibc.applications.rate_limiting.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "ibc.applications.rate_limiting.v1.QueryRateLimitsByChainIDRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/ibc.applications.rate_limiting.v1.QueryRateLimitsByChainIDRequest".into()
    }
}
/// QueryRateLimitsByChainIDResponse returns all rate-limits by a chain.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryRateLimitsByChainIdResponse {
    #[prost(message, repeated, tag = "1")]
    pub rate_limits: ::prost::alloc::vec::Vec<RateLimit>,
}
impl ::prost::Name for QueryRateLimitsByChainIdResponse {
    const NAME: &'static str = "QueryRateLimitsByChainIDResponse";
    const PACKAGE: &'static str = "ibc.applications.rate_limiting.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "ibc.applications.rate_limiting.v1.QueryRateLimitsByChainIDResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/ibc.applications.rate_limiting.v1.QueryRateLimitsByChainIDResponse".into()
    }
}
/// Queries all the rate limits for a given channel or client ID
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryRateLimitsByChannelOrClientIdRequest {
    #[prost(string, tag = "1")]
    pub channel_or_client_id: ::prost::alloc::string::String,
}
impl ::prost::Name for QueryRateLimitsByChannelOrClientIdRequest {
    const NAME: &'static str = "QueryRateLimitsByChannelOrClientIDRequest";
    const PACKAGE: &'static str = "ibc.applications.rate_limiting.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "ibc.applications.rate_limiting.v1.QueryRateLimitsByChannelOrClientIDRequest"
            .into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/ibc.applications.rate_limiting.v1.QueryRateLimitsByChannelOrClientIDRequest"
            .into()
    }
}
/// QueryRateLimitsByChannelOrClientIDResponse returns all rate-limits by a channel or client id.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryRateLimitsByChannelOrClientIdResponse {
    #[prost(message, repeated, tag = "1")]
    pub rate_limits: ::prost::alloc::vec::Vec<RateLimit>,
}
impl ::prost::Name for QueryRateLimitsByChannelOrClientIdResponse {
    const NAME: &'static str = "QueryRateLimitsByChannelOrClientIDResponse";
    const PACKAGE: &'static str = "ibc.applications.rate_limiting.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "ibc.applications.rate_limiting.v1.QueryRateLimitsByChannelOrClientIDResponse"
            .into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/ibc.applications.rate_limiting.v1.QueryRateLimitsByChannelOrClientIDResponse"
            .into()
    }
}
/// Queries all blacklisted denoms
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct QueryAllBlacklistedDenomsRequest {}
impl ::prost::Name for QueryAllBlacklistedDenomsRequest {
    const NAME: &'static str = "QueryAllBlacklistedDenomsRequest";
    const PACKAGE: &'static str = "ibc.applications.rate_limiting.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "ibc.applications.rate_limiting.v1.QueryAllBlacklistedDenomsRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/ibc.applications.rate_limiting.v1.QueryAllBlacklistedDenomsRequest".into()
    }
}
/// QueryAllBlacklistedDenomsResponse returns all the blacklisted denosm.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryAllBlacklistedDenomsResponse {
    #[prost(string, repeated, tag = "1")]
    pub denoms: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
impl ::prost::Name for QueryAllBlacklistedDenomsResponse {
    const NAME: &'static str = "QueryAllBlacklistedDenomsResponse";
    const PACKAGE: &'static str = "ibc.applications.rate_limiting.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "ibc.applications.rate_limiting.v1.QueryAllBlacklistedDenomsResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/ibc.applications.rate_limiting.v1.QueryAllBlacklistedDenomsResponse".into()
    }
}
/// Queries all whitelisted address pairs
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct QueryAllWhitelistedAddressesRequest {}
impl ::prost::Name for QueryAllWhitelistedAddressesRequest {
    const NAME: &'static str = "QueryAllWhitelistedAddressesRequest";
    const PACKAGE: &'static str = "ibc.applications.rate_limiting.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "ibc.applications.rate_limiting.v1.QueryAllWhitelistedAddressesRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/ibc.applications.rate_limiting.v1.QueryAllWhitelistedAddressesRequest".into()
    }
}
/// QueryAllWhitelistedAddressesResponse returns all whitelisted pairs.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryAllWhitelistedAddressesResponse {
    #[prost(message, repeated, tag = "1")]
    pub address_pairs: ::prost::alloc::vec::Vec<WhitelistedAddressPair>,
}
impl ::prost::Name for QueryAllWhitelistedAddressesResponse {
    const NAME: &'static str = "QueryAllWhitelistedAddressesResponse";
    const PACKAGE: &'static str = "ibc.applications.rate_limiting.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "ibc.applications.rate_limiting.v1.QueryAllWhitelistedAddressesResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/ibc.applications.rate_limiting.v1.QueryAllWhitelistedAddressesResponse".into()
    }
}
/// Generated client implementations.
#[cfg(feature = "client")]
pub mod query_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Query defines the gRPC querier service.
    #[derive(Debug, Clone)]
    pub struct QueryClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    #[cfg(feature = "transport")]
    impl QueryClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> QueryClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> QueryClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            QueryClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Queries all rate limits
        pub async fn all_rate_limits(
            &mut self,
            request: impl tonic::IntoRequest<super::QueryAllRateLimitsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::QueryAllRateLimitsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/ibc.applications.rate_limiting.v1.Query/AllRateLimits",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "ibc.applications.rate_limiting.v1.Query",
                        "AllRateLimits",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Queries a specific rate limit by channel ID and denom
        /// Ex:
        ///  - /ratelimit/{channel_or_client_id}/by_denom?denom={denom}
        pub async fn rate_limit(
            &mut self,
            request: impl tonic::IntoRequest<super::QueryRateLimitRequest>,
        ) -> std::result::Result<
            tonic::Response<super::QueryRateLimitResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/ibc.applications.rate_limiting.v1.Query/RateLimit",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "ibc.applications.rate_limiting.v1.Query",
                        "RateLimit",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Queries all the rate limits for a given chain
        pub async fn rate_limits_by_chain_id(
            &mut self,
            request: impl tonic::IntoRequest<super::QueryRateLimitsByChainIdRequest>,
        ) -> std::result::Result<
            tonic::Response<super::QueryRateLimitsByChainIdResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/ibc.applications.rate_limiting.v1.Query/RateLimitsByChainID",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "ibc.applications.rate_limiting.v1.Query",
                        "RateLimitsByChainID",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Queries all the rate limits for a given channel ID
        pub async fn rate_limits_by_channel_or_client_id(
            &mut self,
            request: impl tonic::IntoRequest<
                super::QueryRateLimitsByChannelOrClientIdRequest,
            >,
        ) -> std::result::Result<
            tonic::Response<super::QueryRateLimitsByChannelOrClientIdResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/ibc.applications.rate_limiting.v1.Query/RateLimitsByChannelOrClientID",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "ibc.applications.rate_limiting.v1.Query",
                        "RateLimitsByChannelOrClientID",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Queries all blacklisted denoms
        pub async fn all_blacklisted_denoms(
            &mut self,
            request: impl tonic::IntoRequest<super::QueryAllBlacklistedDenomsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::QueryAllBlacklistedDenomsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/ibc.applications.rate_limiting.v1.Query/AllBlacklistedDenoms",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "ibc.applications.rate_limiting.v1.Query",
                        "AllBlacklistedDenoms",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Queries all whitelisted address pairs
        pub async fn all_whitelisted_addresses(
            &mut self,
            request: impl tonic::IntoRequest<super::QueryAllWhitelistedAddressesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::QueryAllWhitelistedAddressesResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/ibc.applications.rate_limiting.v1.Query/AllWhitelistedAddresses",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "ibc.applications.rate_limiting.v1.Query",
                        "AllWhitelistedAddresses",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
#[cfg(feature = "server")]
pub mod query_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with QueryServer.
    #[async_trait]
    pub trait Query: std::marker::Send + std::marker::Sync + 'static {
        /// Queries all rate limits
        async fn all_rate_limits(
            &self,
            request: tonic::Request<super::QueryAllRateLimitsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::QueryAllRateLimitsResponse>,
            tonic::Status,
        >;
        /// Queries a specific rate limit by channel ID and denom
        /// Ex:
        ///  - /ratelimit/{channel_or_client_id}/by_denom?denom={denom}
        async fn rate_limit(
            &self,
            request: tonic::Request<super::QueryRateLimitRequest>,
        ) -> std::result::Result<
            tonic::Response<super::QueryRateLimitResponse>,
            tonic::Status,
        >;
        /// Queries all the rate limits for a given chain
        async fn rate_limits_by_chain_id(
            &self,
            request: tonic::Request<super::QueryRateLimitsByChainIdRequest>,
        ) -> std::result::Result<
            tonic::Response<super::QueryRateLimitsByChainIdResponse>,
            tonic::Status,
        >;
        /// Queries all the rate limits for a given channel ID
        async fn rate_limits_by_channel_or_client_id(
            &self,
            request: tonic::Request<super::QueryRateLimitsByChannelOrClientIdRequest>,
        ) -> std::result::Result<
            tonic::Response<super::QueryRateLimitsByChannelOrClientIdResponse>,
            tonic::Status,
        >;
        /// Queries all blacklisted denoms
        async fn all_blacklisted_denoms(
            &self,
            request: tonic::Request<super::QueryAllBlacklistedDenomsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::QueryAllBlacklistedDenomsResponse>,
            tonic::Status,
        >;
        /// Queries all whitelisted address pairs
        async fn all_whitelisted_addresses(
            &self,
            request: tonic::Request<super::QueryAllWhitelistedAddressesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::QueryAllWhitelistedAddressesResponse>,
            tonic::Status,
        >;
    }
    /// Query defines the gRPC querier service.
    #[derive(Debug)]
    pub struct QueryServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> QueryServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for QueryServer<T>
    where
        T: Query,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/ibc.applications.rate_limiting.v1.Query/AllRateLimits" => {
                    #[allow(non_camel_case_types)]
                    struct AllRateLimitsSvc<T: Query>(pub Arc<T>);
                    impl<
                        T: Query,
                    > tonic::server::UnaryService<super::QueryAllRateLimitsRequest>
                    for AllRateLimitsSvc<T> {
                        type Response = super::QueryAllRateLimitsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::QueryAllRateLimitsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Query>::all_rate_limits(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = AllRateLimitsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/ibc.applications.rate_limiting.v1.Query/RateLimit" => {
                    #[allow(non_camel_case_types)]
                    struct RateLimitSvc<T: Query>(pub Arc<T>);
                    impl<
                        T: Query,
                    > tonic::server::UnaryService<super::QueryRateLimitRequest>
                    for RateLimitSvc<T> {
                        type Response = super::QueryRateLimitResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::QueryRateLimitRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Query>::rate_limit(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = RateLimitSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/ibc.applications.rate_limiting.v1.Query/RateLimitsByChainID" => {
                    #[allow(non_camel_case_types)]
                    struct RateLimitsByChainIDSvc<T: Query>(pub Arc<T>);
                    impl<
                        T: Query,
                    > tonic::server::UnaryService<super::QueryRateLimitsByChainIdRequest>
                    for RateLimitsByChainIDSvc<T> {
                        type Response = super::QueryRateLimitsByChainIdResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                super::QueryRateLimitsByChainIdRequest,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Query>::rate_limits_by_chain_id(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = RateLimitsByChainIDSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/ibc.applications.rate_limiting.v1.Query/RateLimitsByChannelOrClientID" => {
                    #[allow(non_camel_case_types)]
                    struct RateLimitsByChannelOrClientIDSvc<T: Query>(pub Arc<T>);
                    impl<
                        T: Query,
                    > tonic::server::UnaryService<
                        super::QueryRateLimitsByChannelOrClientIdRequest,
                    > for RateLimitsByChannelOrClientIDSvc<T> {
                        type Response = super::QueryRateLimitsByChannelOrClientIdResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                super::QueryRateLimitsByChannelOrClientIdRequest,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Query>::rate_limits_by_channel_or_client_id(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = RateLimitsByChannelOrClientIDSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/ibc.applications.rate_limiting.v1.Query/AllBlacklistedDenoms" => {
                    #[allow(non_camel_case_types)]
                    struct AllBlacklistedDenomsSvc<T: Query>(pub Arc<T>);
                    impl<
                        T: Query,
                    > tonic::server::UnaryService<
                        super::QueryAllBlacklistedDenomsRequest,
                    > for AllBlacklistedDenomsSvc<T> {
                        type Response = super::QueryAllBlacklistedDenomsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                super::QueryAllBlacklistedDenomsRequest,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Query>::all_blacklisted_denoms(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = AllBlacklistedDenomsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/ibc.applications.rate_limiting.v1.Query/AllWhitelistedAddresses" => {
                    #[allow(non_camel_case_types)]
                    struct AllWhitelistedAddressesSvc<T: Query>(pub Arc<T>);
                    impl<
                        T: Query,
                    > tonic::server::UnaryService<
                        super::QueryAllWhitelistedAddressesRequest,
                    > for AllWhitelistedAddressesSvc<T> {
                        type Response = super::QueryAllWhitelistedAddressesResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                super::QueryAllWhitelistedAddressesRequest,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Query>::all_whitelisted_addresses(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = AllWhitelistedAddressesSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for QueryServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "ibc.applications.rate_limiting.v1.Query";
    impl<T> tonic::server::NamedService for QueryServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
/// GenesisState defines the ratelimit module's genesis state.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GenesisState {
    #[prost(message, repeated, tag = "1")]
    pub rate_limits: ::prost::alloc::vec::Vec<RateLimit>,
    #[prost(message, repeated, tag = "2")]
    pub whitelisted_address_pairs: ::prost::alloc::vec::Vec<WhitelistedAddressPair>,
    #[prost(string, repeated, tag = "3")]
    pub blacklisted_denoms: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "4")]
    pub pending_send_packet_sequence_numbers: ::prost::alloc::vec::Vec<
        ::prost::alloc::string::String,
    >,
    #[prost(message, optional, tag = "5")]
    pub hour_epoch: ::core::option::Option<HourEpoch>,
}
impl ::prost::Name for GenesisState {
    const NAME: &'static str = "GenesisState";
    const PACKAGE: &'static str = "ibc.applications.rate_limiting.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "ibc.applications.rate_limiting.v1.GenesisState".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/ibc.applications.rate_limiting.v1.GenesisState".into()
    }
}
